Reversion to revision 1.12 state.
Change produced non-intuitive error.

diff --git a/zfsrep b/zfsrep
--- a/zfsrep
+++ b/zfsrep
@@ -1,6 +1,6 @@
 #!/bin/sh -
 #
-# $Id: zfsrep,v 1.13 2012/06/23 13:15:25 awaters Exp $
+# $Id: zfsrep,v 1.14 2012/06/23 14:30:50 awaters Exp $
 #
 ############################################################################
 #
@@ -219,7 +219,10 @@ if [ "$?" -eq "0" ]; then
     start=$lastrep
 else
     if [ ! -z "$lastrep" ]; then
-        lastrep=
+        echo "$progname: The last-replicated snapshot \"$destpool@$lastrep\" no longer exists on \"$srcpool\"."
+		echo "$progname: Unable to do an incremental replication. Exiting."
+        expool
+        exit 1
     fi  
 fi
 
