Implement destpool scrub option, add comments.

diff --git a/zfsrep b/zfsrep
--- a/zfsrep
+++ b/zfsrep
@@ -1,12 +1,12 @@
 #!/bin/sh -
 #
-# $Id: zfsrep,v 1.5 2012/03/03 11:56:45 e52202 Exp $
+# $Id: zfsrep,v 1.6 2012/04/01 13:29:36 awaters Exp $
 #
 ############################################################################
 #
 # zfsrep
 #
-# Usage: zfsrep [-m] -s snapname srcpool destpool
+# Usage: zfsrep [-m] [-S] -s snapname srcpool destpool
 #
 # This script automates incremental ZFS snapshot replication, but is really
 # specific to my particular setup; hence the "-m Import destination pool"
@@ -16,13 +16,21 @@
 # bidder for Microserver components, HP?
 #
 # If '-m' was specified and the import successfuly, the pool will be
-# exported prior to script exit.  If '-m' is not specified, the script will
-# exit if the pool is not already imported, and will not export the pool if
-# the pool was mounted.
+# exported prior to script exit, unless "-S" was specified, in which case
+# the pool will be scrubbed and left online for a human to check the status
+# later.  If '-m' is not specified, the script will exit if the pool is not
+# already imported, and will not export the pool if the pool was mounted.
 #
 # "snapname" is more a "type" (eg "weekly") than the actual full name as
 # there are likely more than one snapshot of a particular type. Hence
 # the whole idea of an script that works on incremental snapshots.
+#
+# Assumption: This script will be used to replicate online pools. If
+#             "srcpool" is not online the script will exit. Checks for
+#             an online state may be considered inadequate in the script's
+#             current state.  The script also requires you to be running
+#             FreeBSD 9 or higher; it is untested on FreeBSD 8, nor is it
+#             tested on Solaris.
 #
 # Author: Adrian Waters <awaters@draenan.net>
 #
@@ -35,19 +43,32 @@ PATH=/bin:/usr/bin
 progname=${0##*/}
 
 usage () {
-    echo "Usage: $progname [-m] -s snapname srcpool destpool" >&2
+    echo "Usage: $progname [-m] [-S] -s snapname srcpool destpool" >&2
     exit 1
 }
 
+
+# The expool function will either kick off a scrub of the destination pool,
+# or export the pool, depending on the options chosen by the user.
+
 expool () {
-    if [ ! -z "$imported" ]; then
+    if [ ! -z "$scrubdest" ]; then
+        imported=
+        $ZFS scrub $destpool
+    else
+        if [ ! -z "$imported" ]; then
         $ZPOOL export $destpool > /dev/null 2>&1
             if [ "$?" -ne "0" ]; then
                 echo "$progname: Could not export \"$destpool\". Exiting." >&2
                 exit 1
             fi
+        fi
     fi
 }
+
+# There isn't any reason that I can think of why this script wouldn't work on
+# FreeBSD RELENG_8 or Solaris 10+, I simply haven't tested it. Plus the
+# pool-mounting logic is *very* specific to my own FreeBSD 9 system.
 
 case $(/usr/bin/uname -sr) in
     "FreeBSD 9"*)
@@ -75,10 +96,13 @@ if [ $($ID -u) -ne "0" ]; then
     exit 1
 fi
 
-snapname= import= srcpool= destpool=
+scrubdest= snapname= import= srcpool= destpool=
 
-while getopts :ms: opt; do
+while getopts :mSs: opt; do
     case $opt in
+        S)
+            scrubdest=1
+            ;;
         s)
             snapname=$OPTARG
             ;;
@@ -97,16 +121,34 @@ shift $((OPTIND - 1))
 srcpool=$1
 destpool=$2
 
+# All three of "srcpool", "destpool", and "snapname" must be provided.
+
 if [ -z "$srcpool" -o -z "$destpool" -o -z "$snapname" ]; then
     usage
     exit 1
 fi
+
+# Sanitize the input for "snapname."
+#
+# Note that the ":" character is valid for ZFS snapshot names, 
+# but will cause issues if you are sharing that filesystem via
+# Samba and expect to be able to access snapshots from the ".zfs"
+# directory.  This problem does not exist on Solaris as SMB sharing
+# is intgrated via the ZFS "sharesmb" option, with ":" being
+# automatically translated to "_".  As this script is intended for
+# FreeBSD it treates ":" as an invalid character.
 
 echo $snapname | $GREP -E '[^-_.:[:alnum:]]' > /dev/null 2>&1
 if [ "$?" -eq "0" ]; then
     echo "$progname: \"$snapname\" is not a valid ZFS snapshot name." >&2
     exit 1
 fi
+
+# Sanitize the inputs for "srcpool" and "destpool".
+#
+# The script will not progress if the source pool is not available.  If the
+# destination pool is unavailable an attempt will be made to import it (if
+# requested via the "-m" option), otherwise the script will exit.
 
 for pool in $srcpool $destpool; do
     echo $pool | $GREP -E '^(c[0-9].*|mirror|raidz|spare|log)$|[^-_.[:alnum:]]' > /dev/null 2>&1
@@ -122,8 +164,13 @@ for pool in $srcpool $destpool; do
         else
             $ZPOOL import $destpool > /dev/null 2>&1
             if [ "$?" -ne "0" ]; then
+
                 # Interesting idea below, but ultimately pointless, and wrong if a USB
                 # disk is plugged in. Hard-coding instead.
+                #
+                # This section of code will need to be isolated should I convert this
+                # script to one suitable for systems other than my own.
+
                 #busno=$($CAMCONTROL devlist | $AWK 'END { sub(/scbus/,""); print $5+1 }')
                 busno=6
                 ($CAMCONTROL reset $busno && $CAMCONTROL rescan $busno) > /dev/null 2>&1
@@ -142,6 +189,11 @@ for pool in $srcpool $destpool; do
     fi
 done
 
+# Get a list of all snapshots that match "snapname" on the source and
+# destination pools.  Compare the last snapshot on the source pool to the last
+# replicated snapshot on the destination pool.  If the same, no need to do
+# anything.
+
 snaps=$($ZFS list -r -t snapshot -H -o name -s creation $srcpool | $GREP "$srcpool@$snapname" | $SED "s/$srcpool@//")
 lastsnap=$(echo $snaps | $AWK '{ print $NF }')
 lastrep=$($ZFS list -r -t snapshot -H -o name -s creation $destpool | $GREP "$destpool@$snapname" | $AWK -F@ 'END { print $NF }')
@@ -152,6 +204,12 @@ if [ "X$lastsnap" == "X$lastrep" ]; then
     exit 1
 fi
 
+# Check that the last replicated snapshot is still available on the source
+# pool.  If not (presumably because there is a rolling snapshot schedule in
+# place and the replication hasn't happened in time for the last rep to fall
+# off the list) don't do anything as we can't perform incremental replication
+# from a non-existant source.
+
 echo $snaps | $GREP $lastrep > /dev/null 2>&1
 if [ "$?" -eq "0" ]; then
     start=$lastrep
@@ -160,6 +218,12 @@ else
     expool
     exit 1
 fi
+
+# Perform the incremental snapshot replication between the source and
+# destination pools. Once done, scrub or export the destination pool
+# as required. Ideally I should check for errors here but can't
+# currently think of how to retrieve exit codes from both sides of a
+# pipe.
 
 $ZFS send -R -I $srcpool@$start $srcpool@$lastsnap | $ZFS recv -d -F $destpool
 expool
